services:
  vz-db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: Welcome123
      POSTGRES_DB: DBFlats
    volumes:
    - .\db\1_newtableflats.sql:/docker-entrypoint-initdb.d/1_newtableflats.sql
    - .\db\2_insert.sql:/docker-entrypoint-initdb.d/2_insert.sql
#    networks:
#      - db_network

  vz-httpserver:
    build: .\web\
    ports:
      - "8080:80"
    depends_on:
      - vz-db
#    networks:
#      - db_network

#  adminer:
#    image: adminer
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - 8081:8080

  scraper:
    build: .\sreality_scrapper\
#    restart: always
    depends_on:
      - vz-httpserver
#    ports:
#      - "5432:5432"

#networks:
#  db_network:
##    external: true
#    name: db_network