services:
  vz-db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: Welcome123
      POSTGRES_DB: DBFlats
    volumes:
    - .\db\1_newtableflats.sql:/docker-entrypoint-initdb.d/1_newtableflats.sql
    - .\db\2_insert.sql:/docker-entrypoint-initdb.d/2_insert.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker -d DBFlats" ]
      interval: 10s
      timeout: 5s
      retries: 5


  vz-httpserver:
    build: .\web\
    ports:
      - "8080:80"
    depends_on:
      vz-db:
        condition: service_healthy


  scraper:
    build: .\sreality_scrapper\
#    restart: always
    depends_on:
      vz-db:
        condition: service_healthy
